### ISSUE TITLE
[BUILD] Ability to embed DS styles into other projects

### ISSUE THREAD

**Issue by k1eu** [Selleo/design-system#55]
## Short overview
We do have some components now! Time to make use of the and prepare a way for it! We'd like to be able to embed DS styles into other projects then to be able to just copy paste the ready to use styles. For now we can skip the whole npm integration and deliver it statically.
Example usage (right image):
![image](https://user-images.githubusercontent.com/32620457/220174844-5f5725f1-f6a0-44da-b58d-b29ff2e5ab2e.png)

## ToDo

- [ ] prepare a buildstep of DS components
- [ ] serve styles to be able to consume them in projects
- [ ] add `How to use?` paragraph in readme.md

## Deadline
ASAP

## Contact points
@k1eu

## Notes
For future plans there will be
- integration with npm to install it
- two installations
- - for projects using tailwind (we will need it as a taliwind config plugin)
- - for project without tailwind (the thing we're doing right now)
