### ISSUE TITLE
Small visual fixes

### ISSUE THREAD

**Issue by k1eu** [Selleo/design-system#83]
## Short overview
Task aggregating small fixes & improvements

## ToDo

- [x] Padding on mobile menu should be higher
![image](https://user-images.githubusercontent.com/32620457/225262542-c3ab2d05-c822-4fbc-89d0-a96c84a3b264.png)
- [x] Table of content can be hidden for now
![image](https://user-images.githubusercontent.com/32620457/225262672-78d8ab74-d86e-4837-ba1d-20342c5290bd.png)
- [x] Fix edit this page on index page
![image](https://user-images.githubusercontent.com/32620457/225262739-cef20787-204b-4664-b859-f438e4a8c635.png)
- [x] Add `Getting Started` item at the top of the menu without section. It should redirect to main page
- [x] Paragraphs have wrong HTML
![image](https://user-images.githubusercontent.com/32620457/225270313-173c6463-53c3-4a63-a309-645702c1e03c.png)
- [x] investigate <img /> (might be the parser issue ) wrong HTML (avatar component)

## Contact points
@k1eu

**Comment by PoslinskiNet** [comment]
`<img` also has wrong html @k1eu (avatar I guess)

**Comment by k1eu** [comment]
Added to the list
