### ISSUE TITLE
Create read me/documentation for Selleo design

### ISSUE THREAD

**Issue by michalgren** [Selleo/design-system#93]
## Short overview
Prepare the appropriate documentation and read me regarding the design of Selleo, combine all the files and resourcements we use such as

- Design System, Branding, Website, Dashboard, booking app, kick-off template, all Icons files 
- Customer press kits
- Photos ready to use 
- All workshops e.g. Figma handoff etc.

## ToDo

- [ ] Read me for Selleo design 
- [ ] Finish [Guide to figma presentation](https://www.figma.com/file/5knQq0kvgvRk1l5jbDPtsk/Foundations-presentations?node-id=12-27&t=lcex76HDFHhaKZ6Y-11)
- [ ] Finish [Figma setup presentation](https://www.figma.com/file/5knQq0kvgvRk1l5jbDPtsk/Foundations-presentations?node-id=238-115&t=lcex76HDFHhaKZ6Y-11)
- [ ] Finish [Design process presentation](https://www.figma.com/file/5knQq0kvgvRk1l5jbDPtsk/Foundations-presentations?node-id=275-4308&t=lcex76HDFHhaKZ6Y-11)
- [ ] Finish [How to handoff for dev](https://www.figma.com/file/5knQq0kvgvRk1l5jbDPtsk/Foundations-presentations?node-id=255-4383&t=lcex76HDFHhaKZ6Y-11)
- [ ] aggregate all files, resources and links
