### ISSUE TITLE
Complete the design system with the missing things

### ISSUE THREAD

**Issue by michalgren** [Selleo/design-system#96]
## Short overview
Based on @qbart feedback it would be nice to add additional designs to our design system.
## ToDo
- [ ] Add additional shades of secondary/primary colors
- [ ] Error state in inputs, currently we have error state with a hint below input BUT it needs a bit changes: Change font to Sofia Pro, prepare forms to handoff as we can see nobody knows about that hint below input.
- [ ] Empty checkbox (without label) doesn't have proper error state
- [ ] Problem with copying logo will probably be completed within that task https://github.com/Selleo/design-system/issues/94
- [ ] Prepare a example form with couple of inputs,checkbox etc. and different states

## Contact points
@michalgren @qbart
