### ISSUE TITLE
Create tailwind preset from our tailwind config

### ISSUE THREAD

**Issue by k1eu** [Selleo/design-system#97]
## Short overview
Tailwind supports something like presets in its tailwind config plugin, so we'd like to export our tailwind-config package to npm so it can be used easier in tailwind enabled repositories. 

## ToDo
- [ ] Research about how presets work
- [ ] Release current version as npm package
- [ ] Ensure that it's working on an example project
- [ ] Add action (project uses changesets but they are not configured) that will update the npm package when something changes in the config
- [ ] Guide @qbart how to update his current project to support the new integration system

## Deadline
nice to have for better integration

## Contact points
@k1eu
@qbart has a app running that could benefit from it
