### ISSUE TITLE
Logo - SVG Improvements

### ISSUE THREAD

**Issue by k1eu** [Selleo/design-system#98]
## Short overview
Currently we're only displaying our logo and there's no possibilty to quickly grab it for upcoming users. We'd like to enhance that experience by

- adding possiblity to copy logo as SVG
- adding possibilty to download logo as SVG and PNG

Everything logo related can be found on figma here : 
https://www.figma.com/file/aAZNLti1x7RHcKO2aaVdyh/Selleo-Design-System?type=design&node-id=1473-2313&mode=design&t=OXUdvHdaQ3pb0DkC-4

Can be implemented similarily to Icons https://designsystem.selleo.com/icons/

## ToDo
<!-

- [ ] add possiblity to copy logo as SVG
- [ ] add possibilty to download logo as SVG
- [ ] add possibilty to download logo as PNG

## Deadline
asap

## Contact points
@k1eu
@czana 
 
 ## Notes
 Probably icons will have to be copied to Docs app, to public folder for the ability to download it. But I might be wrong just leaving it as a possbility :)
